import PptxGenJS from "pptxgenjs";

const COLORS = {
  navy: "0F172A",
  blue: "2563EB",
  blueLight: "EFF6FF",
  blueSoft: "DBEAFE",
  text: "1E293B",
  muted: "64748B",
  white: "FFFFFF",
  border: "E2E8F0",
  card: "F8FAFC",
};

const addFooter = (slide, slideNumber) => {
  slide.addText("Generated by SynoraAI", {
    x: 0.55,
    y: 7.08,
    w: 3.1,
    h: 0.18,
    fontFace: "Aptos",
    fontSize: 8,
    color: COLORS.muted,
    margin: 0,
  });

  slide.addText(String(slideNumber), {
    x: 12.25,
    y: 7.08,
    w: 0.55,
    h: 0.18,
    fontFace: "Aptos",
    fontSize: 8,
    color: COLORS.muted,
    align: "right",
    margin: 0,
  });
};

const addHeader = (
  slide,
  pptx,
  title,
  slideNumber,
  sectionLabel = ""
) => {
  if (sectionLabel) {
    slide.addText(sectionLabel.toUpperCase(), {
      x: 0.7,
      y: 0.3,
      w: 4,
      h: 0.25,
      fontFace: "Aptos",
      fontSize: 9,
      bold: true,
      color: COLORS.blue,
      charSpacing: 1.2,
      margin: 0,
    });
  }

  slide.addText(title || "Presentation", {
    x: 0.7,
    y: 0.62,
    w: 10.9,
    h: 0.55,
    fontFace: "Aptos Display",
    fontSize: 27,
    bold: true,
    color: COLORS.navy,
    margin: 0,
  });

  slide.addShape(pptx.ShapeType.line, {
    x: 0.7,
    y: 1.25,
    w: 11.9,
    h: 0,
    line: {
      color: COLORS.border,
      width: 1,
    },
  });

  addFooter(slide, slideNumber);
};

const addBullet = (
  slide,
  pptx,
  text,
  x,
  y,
  w,
  h
) => {
  slide.addShape(pptx.ShapeType.ellipse, {
    x,
    y: y + 0.12,
    w: 0.12,
    h: 0.12,
    fill: {
      color: COLORS.blue,
    },
    line: {
      color: COLORS.blue,
    },
  });

  slide.addText(String(text), {
    x: x + 0.25,
    y,
    w,
    h,
    fontFace: "Aptos",
    fontSize: 16,
    color: COLORS.text,
    margin: 0,
    valign: "mid",
    fit: "shrink",
  });
};

const addSection = (
  pptx,
  section,
  slideNumber,
  sectionIndex
) => {
  const slide = pptx.addSlide();

  slide.background = {
    color: COLORS.white,
  };

  addHeader(
    slide,
    pptx,
    section.heading,
    slideNumber,
    `Section ${String(sectionIndex).padStart(2, "0")}`
  );

  if (section.description) {
    slide.addText(section.description, {
      x: 0.75,
      y: 1.5,
      w: 11.5,
      h: 0.5,
      fontFace: "Aptos",
      fontSize: 14,
      color: COLORS.muted,
      margin: 0,
      fit: "shrink",
    });
  }

  const points = section.points || [];

  const startY = section.description
    ? 2.15
    : 1.65;

  const cardWidth = 5.65;

  const cardHeight = points.length <= 4
    ? 1
    : 0.85;

  points.forEach((point, index) => {
    const column = index % 2;
    const row = Math.floor(index / 2);

    const x = column === 0
      ? 0.8
      : 6.85;

    const y = startY + row * (cardHeight + 0.25);

    slide.addShape(pptx.ShapeType.roundRect, {
      x,
      y,
      w: cardWidth,
      h: cardHeight,
      fill: {
        color: COLORS.card,
      },
      line: {
        color: COLORS.border,
        width: 1,
      },
    });

    slide.addShape(pptx.ShapeType.rect, {
      x,
      y,
      w: 0.07,
      h: cardHeight,
      fill: {
        color: COLORS.blue,
      },
      line: {
        color: COLORS.blue,
      },
    });

    addBullet(
      slide,
      pptx,
      point,
      x + 0.3,
      y + 0.12,
      cardWidth - 0.55,
      cardHeight - 0.2
    );
  });
};

const generatePpt = async (data) => {
  const pptx = new PptxGenJS();

  pptx.layout = "LAYOUT_WIDE";

  pptx.author = "SynoraAI";
  pptx.company = "SynoraAI";
  pptx.subject = data.title || "Presentation";
  pptx.title = data.title || "Presentation";
  pptx.lang = "en-US";

  pptx.theme = {
    headFontFace: "Aptos Display",
    bodyFontFace: "Aptos",
    lang: "en-US",
  };

  let slideNumber = 1;

  // ============================================
  // COVER
  // ============================================

  {
    const slide = pptx.addSlide();

    slide.background = {
      color: COLORS.navy,
    };

    slide.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 0,
      w: 13.333,
      h: 0.14,
      fill: {
        color: COLORS.blue,
      },
      line: {
        color: COLORS.blue,
      },
    });

    slide.addText("SYNORAAI", {
      x: 0.85,
      y: 0.75,
      w: 3,
      h: 0.3,
      fontFace: "Aptos",
      fontSize: 10,
      bold: true,
      color: "93C5FD",
      charSpacing: 2,
      margin: 0,
    });

    slide.addText(data.title || "Presentation", {
      x: 0.85,
      y: 1.8,
      w: 11.2,
      h: 1.3,
      fontFace: "Aptos Display",
      fontSize: 38,
      bold: true,
      color: COLORS.white,
      margin: 0,
      fit: "shrink",
    });

    slide.addText(data.subtitle || "", {
      x: 0.88,
      y: 3.35,
      w: 9.8,
      h: 0.75,
      fontFace: "Aptos",
      fontSize: 19,
      color: "CBD5E1",
      margin: 0,
      fit: "shrink",
    });

    slide.addShape(pptx.ShapeType.line, {
      x: 0.88,
      y: 4.45,
      w: 2,
      h: 0,
      line: {
        color: COLORS.blue,
        width: 3,
      },
    });

    if (data.author) {
      slide.addText(data.author, {
        x: 0.88,
        y: 5.6,
        w: 5,
        h: 0.35,
        fontFace: "Aptos",
        fontSize: 13,
        color: "E2E8F0",
        margin: 0,
      });
    }

    slide.addText("Generated by SynoraAI", {
      x: 0.88,
      y: 6.45,
      w: 3.5,
      h: 0.25,
      fontFace: "Aptos",
      fontSize: 9,
      color: "94A3B8",
      margin: 0,
    });

    slide.addText("01", {
      x: 12.2,
      y: 6.45,
      w: 0.45,
      h: 0.25,
      fontFace: "Aptos",
      fontSize: 9,
      color: "94A3B8",
      align: "right",
      margin: 0,
    });

    slideNumber++;
  }

  // ============================================
  // INTRODUCTION
  // ============================================

  {
    const slide = pptx.addSlide();

    addHeader(
      slide,
      pptx,
      "Introduction",
      slideNumber,
      "Overview"
    );

    slide.addShape(pptx.ShapeType.roundRect, {
      x: 0.8,
      y: 1.7,
      w: 11.7,
      h: 4.6,
      fill: {
        color: COLORS.blueLight,
      },
      line: {
        color: COLORS.blueSoft,
        width: 1,
      },
    });

    slide.addShape(pptx.ShapeType.rect, {
      x: 0.8,
      y: 1.7,
      w: 0.1,
      h: 4.6,
      fill: {
        color: COLORS.blue,
      },
      line: {
        color: COLORS.blue,
      },
    });

    slide.addText(
      data.introduction ||
        "This presentation provides a structured overview of the topic.",
      {
        x: 1.25,
        y: 2.25,
        w: 10.5,
        h: 3.2,
        fontFace: "Aptos",
        fontSize: 22,
        color: COLORS.text,
        valign: "mid",
        margin: 0,
        fit: "shrink",
      }
    );

    slideNumber++;
  }

  // ============================================
  // AGENDA
  // ============================================

  {
    const slide = pptx.addSlide();

    addHeader(
      slide,
      pptx,
      "Agenda",
      slideNumber,
      "Roadmap"
    );

    const agenda = data.agenda || [];

    agenda.forEach((item, index) => {
      const column = index % 2;
      const row = Math.floor(index / 2);

      const x = column === 0
        ? 0.85
        : 6.85;

      const y = 1.65 + row * 1.25;

      slide.addShape(pptx.ShapeType.roundRect, {
        x,
        y,
        w: 5.55,
        h: 0.95,
        fill: {
          color: COLORS.card,
        },
        line: {
          color: COLORS.border,
          width: 1,
        },
      });

      slide.addText(
        String(index + 1).padStart(2, "0"),
        {
          x: x + 0.25,
          y: y + 0.2,
          w: 0.55,
          h: 0.3,
          fontFace: "Aptos Display",
          fontSize: 18,
          bold: true,
          color: COLORS.blue,
          margin: 0,
        }
      );

      slide.addText(String(item), {
        x: x + 1,
        y: y + 0.22,
        w: 4.2,
        h: 0.45,
        fontFace: "Aptos",
        fontSize: 15,
        color: COLORS.text,
        margin: 0,
        fit: "shrink",
      });
    });

    slideNumber++;
  }

  // ============================================
  // CONTENT SECTIONS
  // ============================================

  const sections = data.sections || [];

  sections.forEach((section, index) => {
    addSection(
      pptx,
      section,
      slideNumber,
      index + 1
    );

    slideNumber++;
  });

  // ============================================
  // KEY TAKEAWAYS
  // ============================================

  {
    const slide = pptx.addSlide();

    addHeader(
      slide,
      pptx,
      "Key Takeaways",
      slideNumber,
      "Conclusion"
    );

    const takeaways =
      data.keyTakeaways || [];

    takeaways.forEach((point, index) => {
      const column = index % 2;
      const row = Math.floor(index / 2);

      const x = column === 0
        ? 0.85
        : 6.85;

      const y = 1.7 + row * 1.35;

      slide.addShape(pptx.ShapeType.roundRect, {
        x,
        y,
        w: 5.55,
        h: 1.05,
        fill: {
          color: COLORS.blueLight,
        },
        line: {
          color: COLORS.blueSoft,
          width: 1,
        },
      });

      slide.addText(
        String(index + 1).padStart(2, "0"),
        {
          x: x + 0.25,
          y: y + 0.28,
          w: 0.45,
          h: 0.3,
          fontFace: "Aptos Display",
          fontSize: 16,
          bold: true,
          color: COLORS.blue,
          margin: 0,
        }
      );

      slide.addText(String(point), {
        x: x + 0.9,
        y: y + 0.2,
        w: 4.2,
        h: 0.6,
        fontFace: "Aptos",
        fontSize: 15,
        color: COLORS.text,
        margin: 0,
        fit: "shrink",
      });
    });

    slideNumber++;
  }

  // ============================================
  // THANK YOU
  // ============================================

  {
    const slide = pptx.addSlide();

    slide.background = {
      color: COLORS.navy,
    };

    slide.addText("THANK YOU", {
      x: 1,
      y: 1.75,
      w: 11.3,
      h: 0.35,
      fontFace: "Aptos",
      fontSize: 10,
      bold: true,
      color: "93C5FD",
      align: "center",
      charSpacing: 2,
      margin: 0,
    });

    slide.addText("Thank You", {
      x: 1,
      y: 2.35,
      w: 11.3,
      h: 0.95,
      fontFace: "Aptos Display",
      fontSize: 40,
      bold: true,
      color: COLORS.white,
      align: "center",
      margin: 0,
    });

    slide.addText(
      data.thankYou ||
        "Thank you for your time and attention.",
      {
        x: 1.4,
        y: 3.55,
        w: 10.5,
        h: 0.65,
        fontFace: "Aptos",
        fontSize: 18,
        color: "CBD5E1",
        align: "center",
        margin: 0,
        fit: "shrink",
      }
    );

    slide.addShape(pptx.ShapeType.line, {
      x: 5.25,
      y: 4.55,
      w: 2.8,
      h: 0,
      line: {
        color: COLORS.blue,
        width: 3,
      },
    });

    slide.addText("Generated by SynoraAI", {
      x: 4.2,
      y: 6.35,
      w: 4.9,
      h: 0.3,
      fontFace: "Aptos",
      fontSize: 10,
      color: "94A3B8",
      align: "center",
      margin: 0,
    });

    slide.addText(String(slideNumber), {
      x: 12.2,
      y: 6.35,
      w: 0.45,
      h: 0.25,
      fontFace: "Aptos",
      fontSize: 9,
      color: "94A3B8",
      align: "right",
      margin: 0,
    });
  }

  return pptx.write({
    outputType: "nodebuffer",
  });
};

export default generatePpt;